name: flutter_server_driven_ui
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  dmrtd:
    path: /Users/maitrunghieu/workspace/work/flutter/dmrtdIDNFC
    # git:
    #   url: https://github.com/hieumt211299/NFC-scan-Passport-IDcard.git
    #   ref: main
    #   auth:
    #     username: hieumt211299
    #     password: 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

  flutter:
    sdk: flutter
  flutter_nfc_kit: ^3.4.2
  flutter_image_compress: ^2.1.0
  google_mlkit_text_recognition: ^0.4.0
  json_dynamic_widget: ^7.0.6+2
  nfc_manager: ^3.3.0
  camera: ^0.10.5+8
  permission_handler: ^11.1.0
  flutter_platform_widgets: ^6.1.0
  expandable: ^5.0.1
  intl: ^0.19.0
  logging: ^1.2.0
  image: ^4.1.7
  mrzscanner_flutter: ^1.0.14
  mrz_parser: ^2.0.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/
